### ISSUE TITLE
"Store uploads in this folder" is on a Subdomain

### ISSUE THREAD

**Issue by benjino** [rvola/wp-original-media-path#1]
"Store uploads in this folder" is on a subdomain. When I point to the subdomain media.mydomain.com/wp-content/uploads it creates those paths inside the root of mydomain.com. 

It doesn't matter what I put in "Store uploads in this folder," it does the same thing every time, all this field does is put whatever I put into it, into the root of mydomain.com

How do I get the Uploads to go to media.mydomain.com/wp-content/uploads???

**Comment by rvola** [comment]
Hello Benjino !
It's simple.

If you leave the original folder location of the upload. Here's what you need to do.

Create the subdomain: media.domain.com and made the point in the wp-content / uploads folder

Activate the plugin and fill like this:
1. field: wp-content / uploads (or no slash at the beginning or at the end)
2. Field: http://media.domain.com

That's all !
Each uploaded image even go to the uploads folder and you can call it with the address http://media.domain.com/2016/09/test.jpg

**Comment by benjino** [comment]
I got it figure out, I posted on WordPress.org http://wordpress.org/ so you can see my solution there.

**Comment by rvola** [comment]
Following in this thread [https://wordpress.org/support/topic/not-uploading-to-subdomain/#post-8137560](https://wordpress.org/support/topic/not-uploading-to-subdomain/#post-8137560)
