### ISSUE TITLE
 Improvement of clean input regex seems to me questionable

### ISSUE THREAD

**Issue by PaulArgoud** [rvola/wp-original-media-path#2]
Hi !

Since version 2.4.1 of the plugin, I encounter a problem with “Store uploaded files in this folder” input. Indeed, my input deliberately started with a slash / in order to use an absolute path.

I guess this is voluntary, but I point it out anyway because if this behavior becomes problematic for me, it can become problematic for other people. Personally, I reinstalled version 2.4.0.

https://github.com/rvola/wp-original-media-path/commit/8d04b49dfcadb7a47bb4481f8eef5d9963878cf2

Have a nice day.

Paul.

**Comment by rvola** [comment]
Hi @PaulArgoud ,
thank you for your return. It is fixed with 355a8a4
